### ISSUE TITLE
Issue with v109 on ArchLinux

### ISSUE THREAD

**Issue by camembert7** [WaferMouse/L3-37#10]
Hello,
I experiment a crash with v109 on ArchLinux, with EDMC v4.2.7 Python v3.9.3

> Traceback (most recent call last):
>   File "/home/ivan/tempo/EDMarketConnector-stable/./EDMarketConnector.py", line 1352, in <module>
>     app = AppWindow(root)
>   File "/home/ivan/tempo/EDMarketConnector-stable/./EDMarketConnector.py", line 499, in __init__
>     theme.apply(self.w)
>   File "/home/ivan/tempo/EDMarketConnector-stable/theme.py", line 320, in apply
>     self._update_widget(widget)
>   File "/home/ivan/tempo/EDMarketConnector-stable/theme.py", line 272, in _update_widget
>     widget.configure(foreground = self.current['highlight']),
>   File "/usr/lib/python3.9/tkinter/__init__.py", line 1646, in configure
>     return self._configure('configure', cnf, kw)
>   File "/usr/lib/python3.9/tkinter/__init__.py", line 1636, in _configure
>     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
**> _tkinter.TclError: unknown option "-foreground"**

extra/tk 8.6.11.1-1
extra/tcl 8.6.11-1 

It looks like [Tk.Label  has evolved](https://stackoverflow.com/questions/60928474/tkinter-tclerror-unknown-option-on-widget-attributes)

Thank you

**Comment by camembert7** [comment]
After an update to EDMC 5 beta, the error is no longer there.

**Comment by camembert7** [comment]
With EDMC 5 beta : error of "ship_map" not found in companion.py

```
2021-04-18 19:14:05.721 - ERROR - 105438:140113688696640:105438 plug.Plugin.__init__:64: : Failed for Plugin "edmc-L3-37"
Traceback (most recent call last):
  File "/home/ivan/tempo/EDMarketConnector-main/plug.py", line 51, in __init__
    module = importlib.machinery.SourceFileLoader('plugin_{}'.format(
  File "<frozen importlib._bootstrap_external>", line 469, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 969, in load_module
  File "<frozen importlib._bootstrap_external>", line 794, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ivan/.local/share/EDMarketConnector/plugins/edmc-L3-37/load.py", line 18, in <module>
    from fleet_monitor import FleetMonitor
  File "/home/ivan/.local/share/EDMarketConnector/plugins/edmc-L3-37/fleet_monitor.py", line 13, in <module>
    from companion import ship_map
ImportError: cannot import name 'ship_map' from 'companion' (/home/ivan/tempo/EDMarketConnector-main/companion.py)
2021-04-18 19:14:05.721 - ERROR - 105438:140113688696640:105438 plug.load_plugins:161: Failure loading found Plugin "edmc-L3-37"

```

**Comment by WaferMouse** [comment]
Fixed as of latest release: https://github.com/WaferMouse/L3-37/releases/tag/110
