### ISSUE TITLE
crashes on linux

### ISSUE THREAD

**Issue by jhernberg** [WaferMouse/L3-37#11]
Hi,

Maybe I'd doing something wrong, but I get this when I try to run the plugin on linux.

2021-05-24 14:58:23.548 - INFO - 3980895:140239546132288:3980895 plug.Plugin.__init__:49: loading plugin "edmc-L3-37" from "/home/jack/.local/share/EDMarketConnector/plugins/edmc-L3-37/load.py"
L3-37 started
Failed to load route data
Chat Viewer loaded
Recon Limpet Controllers is missing!
Research Limpet Controller is missing!
L3-37 loaded
Traceback (most recent call last):
  File "/media/sda4/wineprefix/EDMarketConnector/./EDMarketConnector.py", line 1716, in <module>
    app = AppWindow(root)
  File "/media/sda4/wineprefix/EDMarketConnector/./EDMarketConnector.py", line 581, in __init__
    theme.apply(self.w)
  File "/media/sda4/wineprefix/EDMarketConnector/theme.py", line 320, in apply
    self._update_widget(widget)
  File "/media/sda4/wineprefix/EDMarketConnector/theme.py", line 272, in _update_widget
    widget.configure(foreground = self.current['highlight']),
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-foreground"

**Comment by WaferMouse** [comment]
Are you using the latest version of EDMC?

Does this happen immediately on startup? If not, when does it happen?

Does the EDMC window open?

Does EDMC act correctly if you launch it without the plugin installed?

**Comment by Retrodynen** [comment]
I get the same :(

**Comment by HalJordan** [comment]
Just to be clear, when you say this, do you mean your latest zip, or the latest edmc zip?
 
> In the meantime, you could try downloading the zip from latest release and installing that way. I don't recommend cloning the repo, as it's not necessarily production ready at any given time.

**Comment by WaferMouse** [comment]
Sorry for the delay, peeps. I have a number of IRL issues still ongoing. The good news is that I hope to have a Linux rig setup this evening, so I should be able to look at this soon.

@HalJordan You should follow EDMC's instructions for installing EDMC. The instructions for installing my plugin are as follows and can be found on the main page of the repo:

1. On EDMC's Plugins settings tab press the Open button. This reveals the plugins folder where EDMC looks for plugins.
2. Download the [latest release](https://github.com/WaferMouse/L3-37/releases).
3. Open the .zip archive that you downloaded and move the edmc-L3-37 folder contained inside into the plugins folder.

**Comment by Retrodynen** [comment]
No need to apologise :) thank you for all your work regardless, I hope you're doing alright

**Comment by WaferMouse** [comment]
I have been unable to reproduce this issue on my setup using the main branch. The steps I followed to install (on AntiX, so same steps should work on Debian/Ubuntu etc) are as follows:

1. Install git
2. apt-get the [prerequisites](https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source)
3. Install pyenv using [pyenv-installer](https://github.com/pyenv/pyenv-installer)
4. pyenv install 3.9.5
5. Created a venv and installed the remaining requirements per the [EDMC instructions](https://github.com/EDCD/EDMarketConnector/wiki/Running-from-source).
6. Downloaded the latest release of L3-37 and ran EDMC.

@Retrodynen @HalJordan @jhernberg I recommend reinstalling EDMC whilst following the above instructions as closely as you can. Please let me know the results.

**Comment by WaferMouse** [comment]
Also, is everyone here trying to run EDMC through WINE? I didn't notice this before, but a friend pointed it out to me.

I know that EDMC's own wiki lists running it through WINE as a supported option, but it's a really roundabout way of doing it.

**Comment by WaferMouse** [comment]
Closing due to inactivity and personal disinterest tbh. People shouldn't be running Python apps in WINE, there's no good reason for it.
