### ISSUE TITLE
Not working with latest EDMC

### ISSUE THREAD

**Issue by blueeagle69** [WaferMouse/L3-37#8]
Hi.

Is there any chance of adding support for the latest EDMC?

Thanks.

**Comment by WaferMouse** [comment]
Please ensure that you're using the latest release of the plugin. If you still have problems, please post your log file from %localappdata%\Temp\EDMarketConnector.log

**Comment by ma1uta** [comment]
The same issue.
From the debug log:
```
2021-05-13 21:01:10.500 - INFO - 10416:5908:5908 plug.Plugin.__init__:49: loading plugin "edmc-L3-37" from "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py"
2021-05-13 21:01:10.510 - DEBUG - 10416:5908:5908 config.AbstractConfig.getint:344: Attempt to use Deprecated getint() method
  File "EDMarketConnector.py", line 1705, in <module>
  File "EDMarketConnector.py", line 346, in __init__
  File "plug.pyc", line 159, in load_plugins
  File "plug.pyc", line 51, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 16, in <module>
    from fsd_target import FSDTarget
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\fsd_target.py", line 21, in <module>
    theme = config.getint('theme')
  File "config.pyc", line 344, in getint

2021-05-13 21:01:10.521 - DEBUG - 10416:5908:5908 config.AbstractConfig.get:285: Attempt to use Deprecated get() method
  File "EDMarketConnector.py", line 1705, in <module>
  File "EDMarketConnector.py", line 346, in __init__
  File "plug.pyc", line 159, in load_plugins
  File "plug.pyc", line 51, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 16, in <module>
    from fsd_target import FSDTarget
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\fsd_target.py", line 22, in <module>
    fg = config.get('dark_text') if theme else 'black'
  File "config.pyc", line 285, in get

2021-05-13 21:01:10.521 - DEBUG - 10416:5908:5908 config.AbstractConfig.get:285: Attempt to use Deprecated get() method
  File "EDMarketConnector.py", line 1705, in <module>
  File "EDMarketConnector.py", line 346, in __init__
  File "plug.pyc", line 159, in load_plugins
  File "plug.pyc", line 51, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 16, in <module>
    from fsd_target import FSDTarget
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\fsd_target.py", line 23, in <module>
    hl = config.get('dark_highlight') if theme else 'blue'
  File "config.pyc", line 285, in get

2021-05-13 21:01:10.521 - ERROR - 10416:5908:5908 plug.Plugin.__init__:64: : Failed for Plugin "edmc-L3-37"
Traceback (most recent call last):
  File "plug.pyc", line 51, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 16, in <module>
    from fsd_target import FSDTarget
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\fsd_target.py", line 42, in <module>
    with open(join(config.respath, 'systems.p'),  'rb') as h:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\EDMarketConnector\\systems.p'
2021-05-13 21:01:10.521 - ERROR - 10416:5908:5908 plug.load_plugins:161: Failure loading found Plugin "edmc-L3-37"
Traceback (most recent call last):
  File "plug.pyc", line 159, in load_plugins
  File "plug.pyc", line 51, in __init__
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\load.py", line 16, in <module>
    from fsd_target import FSDTarget
  File "C:\Users\User\AppData\Local\EDMarketConnector\plugins\edmc-L3-37\fsd_target.py", line 42, in <module>
    with open(join(config.respath, 'systems.p'),  'rb') as h:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\EDMarketConnector\\systems.p'
```

**Comment by WaferMouse** [comment]
Fixed as of latest release: https://github.com/WaferMouse/L3-37/releases/tag/110
